#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus        off            \
                focus_follows_mouse        on             \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                window_opacity             on             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      1.0            \
                window_animation_duration  0.5            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                8              \
                bottom_padding             8              \
                left_padding               8              \
                right_padding              8              \
                window_gap                 8              

# Exclude problematic apps from being managed:
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Firefox$" title="Library" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^iPhone Mirroring$" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."

borders active_color=0xff525252 inactive_color=0x80525252 style=rounded hidpi=off width=3.0 blacklist="iPhone Mirroring" &
